f=open("d:/m.txt","r")
print(f.read())
f.close()
f=open("d:/m.txt","w")
print(f.write(input("enter the text")))
f.close()
f=open("d:/m.txt","r")
print(f.read())
f.close()
f=open("d:/m.txt","a")
print(f.write(input("enter the text")))
f.close()
f=open("d:/m.txt","r")
print(f.read())
f.close()
